### ISSUE TITLE
Parent TinyMCE window doesn't automatically resize when switching to edit mode.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/gm2016-grunion-editor#3]
Edit mode on the iframes is longer than normal mode, so the editor will likely need to resize, but I'm unsure how to trigger the autoresize check.

I couldn't seem to get the whole `tinyMCE.activeEditor.execCommand('mceAutoResize');` (spitballing the exact command from memory) thing to work.

cc: @aduth -- you'd commented on a similar issue (I think) a while back over here: https://github.com/tinymce/tinymce/issues/2885

**Comment by aduth** [comment]
I think `wpAutoResize` is the command you want? WordPress uses a forked version of the `autoresize` plugin.

Related: https://github.com/WordPress/WordPress/blob/4a6f90db58a935abb688cfb91b391dffeda7b35c/wp-includes/js/tinymce/plugins/wpautoresize/plugin.js#L202

**Comment by aduth** [comment]
Here's where we use it in the Calypso editor:

https://github.com/Automattic/wp-calypso/blob/a1d9b8c571e0a860ebb90b169ef8f7185415acb5/client/components/tinymce/plugins/media/plugin.jsx#L545

Which is triggered when `load` events are fired from images within the editor frame:

1. https://github.com/Automattic/wp-calypso/blob/a1d9b8c571e0a860ebb90b169ef8f7185415acb5/client/components/tinymce/plugins/media/plugin.jsx#L665
2. https://github.com/Automattic/wp-calypso/blob/a1d9b8c571e0a860ebb90b169ef8f7185415acb5/client/components/tinymce/plugins/media/plugin.jsx#L548-L552
